name: Conditionals Demo

on:
  workflow_dispatch:

jobs:
  continue-on-error-demo:
    runs-on: ubuntu-latest

    steps:
      - name: This step will fail
        continue-on-error: true
        run: |
          echo "This step is failing..."
          exit 1

      - name: Workflow continues
        run: echo "The workflow is still running!"