name: Conditionals Demo

on:
  workflow_dispatch:

jobs:
  branch-condition:
    runs-on: ubuntu-latest

    steps:
      - name: Intentionally fail this step
        run: exit 1

      - name: Runs only when the previous step failed
        if: failure()
        run: echo "Previous step failed."