name: Conditionals Demo

on:
  workflow_dispatch:

jobs:
  branch-condition:
    runs-on: ubuntu-latest

    steps:
      - name: Runs only on the main branch
        if: github.ref == 'refs/heads/main'
        run: echo "Running on the main branch."